ci(workflows): fix
Signed-off-by: Mel Tamplin <contact@meibee.dev>

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,48 +1,73 @@
-name: Deploy to GitHub Pages
+name: Deploy to Pages
 
 on:
   push:
-    branches: [ main ]
-  pull_request:
-    branches: [ main ]
+    branches: [ "main" ]
+  workflow_dispatch:
+
+# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
+permissions:
+  contents: read
+  pages: write
+  id-token: write
+
+# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
+# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
+concurrency:
+  group: "pages"
+  cancel-in-progress: false
 
 jobs:
-  build-and-deploy:
+  build:
     runs-on: ubuntu-latest
-    permissions:
-      contents: read
-      pages: write
-      id-token: write
-
+    defaults:
+      run:
+        working-directory: ./ome-calima
     steps:
-    - name: Checkout
-      uses: actions/checkout@v4
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Detect package manager
+        id: detect-package-manager
+        run: |
+          if [ -f "yarn.lock" ]; then
+           echo "manager=yarn" >> $GITHUB_OUTPUT
+           echo "command=install" >> $GITHUB_OUTPUT
+           echo "runner=yarn" >> $GITHUB_OUTPUT
+           exit 0
+          elif [ -f "package-lock.json" ]; then
+           echo "manager=npm" >> $GITHUB_OUTPUT
+           echo "command=ci" >> $GITHUB_OUTPUT
+           echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+           exit 0
+          else
+           echo "Unable to determine package manager"
+           exit 1
+          fi
+      - name: Setup Node
+        uses: actions/setup-node@v4
+        with:
+          node-version: "22.16.0"
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
+          cache-dependency-path: ./ome-calima/${{ steps.detect-package-manager.outputs.manager == 'npm' && 'package-lock.json' || 'yarn.lock' }}
+      - name: Setup Pages
+        uses: actions/configure-pages@v5
+      - name: Install dependencies
+        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+      - name: Build with Vite
+        run: ${{ steps.detect-package-manager.outputs.runner }} vite build
+      - name: Upload artifact
+        uses: actions/upload-pages-artifact@v4
+        with:
+          path: ./ome-calima/dist
+          retention-days: 0
 
-    - name: Setup Node.js
-      uses: actions/setup-node@v4
-      with:
-        node-version: '18'
-        cache: 'npm'
-        cache-dependency-path: './ome-calima/package-lock.json'
-
-    - name: Install dependencies
-      run: |
-        cd ome-calima
-        npm ci
-
-    - name: Build
-      run: |
-        cd ome-calima
-        npm run build
-
-    - name: Setup Pages
-      uses: actions/configure-pages@v4
-
-    - name: Upload artifact
-      uses: actions/upload-pages-artifact@v3
-      with:
-        path: './ome-calima/dist'
-
-    - name: Deploy to GitHub Pages
-      id: deployment
-      uses: actions/deploy-pages@v4
+  deploy:
+    environment:
+      name: github-pages
+      url: ${{ steps.deployment.outputs.page_url }}
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Deploy to GitHub Pages
+        id: deployment
+        uses: actions/deploy-pages@v4
